# Generated by Django 3.0.7 on 2022-03-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220303_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desgination',
            new_name='designation',
        ),
    ]
